# Generated by Django 4.2.10 on 2026-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emailverificationtoken",
            new_name="accounts_em_user_id_6989e4_idx",
            old_name="accounts_em_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="emailverificationtoken",
            new_name="accounts_em_expires_f36bd3_idx",
            old_name="accounts_em_expires_idx",
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
